### ISSUE TITLE
whitelist.py doesn't skew probability wrt total score

### ISSUE THREAD

**Issue by vinisr** [QuarkChain/crowdsale-whitelist#6]
Line 73 comment is off. It suggested "weighted random sampling" while the code actually simply does a "random sampling".
The probability is definitely not affected by the total score. 
You can even empirically check by making a simple simulation and graph the result out.

Suggestion: 
Either follow up on that comment (73):
Use a built in python 3.6 random module - choices method that support weights.
https://docs.python.org/dev/library/random.html#random.choices

or delete that comment (73)

**Comment by ninjaahhh** [comment]
sorry missed this issue.

let's do a simulation [repl.it](https://repl.it/@ninjaahhh/whitelist) with whitelist size 1, alice with score 50 and bob with score 100, using `random.random` as the seed and run the program for 10000 times.

hit the **run** button, and you will see out of 10000 times, bob actually has twice of the chance to be picked into the whitelist. (`Counter({'bob': 6649, 'alice': 3351})` in my case.)

this method is called [inverse transform sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling) where we can use a uniformly distributed random number to simulate an arbitrary probabilistic distribution.

hope this helps

**Comment by visiblebranch** [comment]
Dear Ninjaahhh,

When you use two users in simulation, the results of using random.random function retrieve a significantly different result for different scores (as you explained earlier)

Unfortunately, with a larger data set (as for in your whitelist with 15k+ users) there is almost no weight given to the scores. random.random function was simply useless for this whitelisting.

Inverse transform sampling is not working with a combination of large data set and random.random function.

This issue was already raised by a github user vinisr (as you can see in an earlier message), however, you didn't follow his advice. His advice was to use random.choice method as explained in python guideline.

I have attached an analysis of actual data and result in an excel file with this message. You can see that the scores have almost no effect on the selection of the winners.

As a consequence of this, thousands of QuarkChain’s loyal community members who actively participated and contributed in the project (by creating videos and blogs) had barely any advantage of doing so. It feels like they were simply used QuarkChain’s hype.

Most importantly, it was told various times by QuarkChain in different steemit articles and in telegram chat that the higher scores will give community members a higher chance of winning. This was simply not done.

I hope you guys are developing blockchain in a better way than your whitelisting. If that is being developed in the same way as whitelist.py, I don’t see quarkchain going any way near the moon.

Thanks[
[quarkchain lottery - Copy.xlsx](https://github.com/QuarkChain/crowdsale-whitelist/files/2086699/quarkchain.lottery.-.Copy.xlsx)
](url)

**Comment by QuarkChain** [comment]
Note sure you really understand the code, but basically random.choices() is do the same thing:

https://github.com/python/cpython/blob/master/Lib/random.py

    def choices(self, population, weights=None, *, cum_weights=None, k=1):
        """Return a k sized list of population elements chosen with replacement.
        If the relative weights or cumulative weights are not specified,
        the selections are made with equal probability.
        """
        random = self.random
        if cum_weights is None:
            if weights is None:
                _int = int
                total = len(population)
                return [population[_int(random() * total)] for i in range(k)]
            cum_weights = list(_itertools.accumulate(weights))
        elif weights is not None:
            raise TypeError('Cannot specify both weights and cumulative weights')
        if len(cum_weights) != len(population):
            raise ValueError('The number of weights does not match the population')
        bisect = _bisect.bisect
        total = cum_weights[-1]
        return [population[bisect(cum_weights, random() * total)] for i in range(k)]

In addition, replacing the code with random.choices() yields the same result.

**Comment by ninjaahhh** [comment]
hi visiblebranch,

let's focus on the code.

1. python's implementation of weighted random choice is a speed-up version of sampling (using bisect ) and *it allows duplicates*. any evidence that inverse transform sampling + big data set won't work?
1. using the same spreadsheet (excellent spreadsheet indeed!), with the whitelist generated by running `random.choices`, we have the distribution of whitelisted participants scores like following, which I don't see much difference

<img width="1444" alt="screen shot 2018-06-08 at 11 42 00 pm" src="https://user-images.githubusercontent.com/38544039/41188858-c8b37170-6b79-11e8-9c3d-75abb0035277.png">

so, allow us to kindly disagree with everything else you said :)

===UPDATE===

to clarify

1. this [PR](https://github.com/QuarkChain/crowdsale-whitelist/pull/4) won't work since it allows duplicates
1. to remove duplicates, as @QuarkChain said, if you replace the the code in our inner loop with `random.choices(..., k=1)` (which means only picking one element), and remove that element and repeat, you should see exactly the same results as our code

**Comment by vinisr** [comment]
Hi there,

Its been a while.
I'm sorry but i really lose all my interest after i saw your demo on the small sample size. Have a good project ahead.
Please consider this issue closed.

**Comment by QuarkChain** [comment]
Interesting.  It is very convenient to ignore the equivalent between our code and random.choices() but rather focusing on sample size ....

**Comment by vinisr** [comment]
Hi QuarkChain,

When you conveniently ignore potential bias in dataset for a simple sampling problem, i really do lose interest in the project. Not to mention, there's no point in debating this anymore.
I sincerely hope you guys will actually come up with an actually working - sharding based - scalability solution. Good luck.
